kind: pipeline
name: default

trigger:
  branch:
    - master
    - feature/*
  event:
#    - tag
    - push

steps:

- name: build-settings
  image: 192.168.110.129:5000/knives/drone-maven-setting:latest
  settings:
    servers:
    - id: oss
      username: yizhishang
      password: Yuanyj@314@888
  when:
    event: push

- name: maven
  image: 192.168.110.129:5000/maven:3-jdk-8
  pull: IfNotPresent
  extra_hosts:
    - "nexus.yizhishang.com:192.168.110.129"
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  volumes:
  - name: MavenCache
    path: /drone/src/repo
  commands:
  - mvn clean deploy -P release -s settings.xml
  - mvn cobertura:cobertura coveralls:report -DrepoToken=uuyFNwxdb4MoRiTDU0BlLOaKrCh3Pp8U9
  when:
    event: push

volumes:
- name: MavenCache
  host:
    path: /mnt/tmp/maven
